global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'api-service'
    static_configs:
      - targets: ['api-serving:8000']

  - job_name: 'model-monitor'
    static_configs:
      - targets: ['model-monitor:8001']
